---
title: "maps_FE"
author: "Edgar"
date: "2024-06-22"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r package upload}
library(ggplot2)
library(tidyr)
library(forcats)
library(dplyr)
library(readxl) 
library(readr)
library(RColorBrewer)
library(tidyverse)
library(binom)
library(lubridate)
library(ade4)
library(ggrepel)
library(broom)
library(ggpubr)
library(rstatix)
library(wesanderson)
library(car)
library(multcompView)
library(rcompanion)
library(writexl)
library(gmodels)
library(openxlsx)
library(fmsb)


#OFW
library(maps)
library(sf)
library(furrr)
library(raster)
library(ggthemes)
library(terra)
library(marmap)
library(rnaturalearth)
library(rnaturalearthdata)
library(rnaturalearthhires)
library(ggspatial)
library(osmdata)
library(grid)
library(geosphere)

```


```{r data import}

ports <- tibble::tribble(
  ~Port,            ~latitude,  ~longitude, ~label_position, ~legend_pt,        ~label_port,              ~country,
  "La Cotinière",    45.91306,   -1.32778,  "left",         "French ports",    "La Cotinière",           "France",
  "Arcachon",        44.65230,   -1.17850,  "left",         "French ports",    "Arcachon",               "France",
  "Bayonne",         43.49000,   -1.48000,  "left",         "French ports",    "Bayonne",                "France",
  "Saint-Jean-de-Luz",43.39000,  -1.66000,  "right",         "French ports",    "Saint-Jean-de-Luz",      "France",
  "Pasaia",          43.32528,   -1.92111,  "below",         "Spanish ports",    "Pasaia",                 "Spain",
  "Ondarroa",        43.32194,   -2.41944,  "below",         "Spanish ports",    "Ondarroa",               "Spain",
  "Bermeo",          43.42083,   -2.72139,  "top",         "Spanish ports",    "Bermeo",                 "Spain",
  "Bilbao",          43.35000,   -3.03333,  "below",         "Spanish ports",    "Bilbao",                 "Spain",
  "Santander",       43.46306,   -3.80444,  "top",         "Spanish ports","Santander",              "Spain"
)
ports

Sampled_beaches <- read_excel("Datasheets/Sampled_beaches.xlsx", na = "NA") %>%
  mutate(latitude = as.numeric(latitude),
         longitude = as.numeric(longitude),
         label_position = ifelse(substr(code, 1, 2) == "FR", "right", "below"),
         legend_pt = ifelse(label_position == "right", "French beaches", "Basque Country beaches")) %>% 
  filter(!is.na(code)) %>% 
   mutate(label_beach = paste(code, Beaches, sep = " = "))
Sampled_beaches

# World polygons from the maps package
world_shp <- sf::st_as_sf(maps::map("world", plot = FALSE, fill = TRUE))

# # Load EEZ polygons
# eezs <- read_sf("Geodata/World_EEZ_v12_20231025", layer = 'eez_v12') %>% 
#   filter(POL_TYPE == '200NM') # select the 200 nautical mile polygon layer
# eezs

# Get high-resolution data for Europe
europe_high_res <- ne_countries(scale = "large", returnclass = "sf", continent = "Europe")
# Get high-resolution coastline data
coastline_high_res <- ne_coastline(scale = "large", returnclass = "sf")
```

```{r}

# Obtenir les données administratives de la France (résolution moyenne)
france_adm1 <- ne_states(country = "france", returnclass = "sf")
france_adm1
# Filtrer pour obtenir la Nouvelle-Aquitaine
nouvelle_aquitaine <- france_adm1 %>% 
  filter(region == "Nouvelle-Aquitaine") %>%
  summarise(geometry = st_union(geometry))

# Obtenir les données administratives de la France (résolution moyenne)
spain_adm1 <- ne_states(country = "spain", returnclass = "sf")
spain_adm1
# Filtrer pour obtenir la Nouvelle-Aquitaine
BC <- spain_adm1 %>% 
  filter(region == "País Vasco") %>%
  summarise(geometry = st_union(geometry))



pt_color <- c("French beaches" = "#0039D8", "Basque Country beaches" = "#009B48")
hb_color <- c("French ports" = "#0039D8", "Spanish ports" = "#009B48")

# Create a data frame for the studied area
studied_area_df <- data.frame(
  xmin = -4.0,
  xmax = -1.0,
  ymin = 43.2,
  ymax = 46.3,
  area = "Studied area"
)

Sampled_beaches$legend_pt <- factor(Sampled_beaches$legend_pt, 
                                    levels = c("French beaches", "Basque Country beaches"))


```


```{r General with harbor}


Plasfito_ports <- ggplot() +
  # Add white background
  geom_rect(aes(xmin = -5.2, xmax = -0.0, ymin = 42.8, ymax = 48.25), 
            fill = "white", color = NA) +
  
  # Add Plasfito area with legend
  geom_rect(data = studied_area_df, aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = area), 
            color = NA, alpha = 1) +
  scale_fill_manual(values = c("Studied area" = "#80CAD0"), name = "") +
  # Add background continent
  geom_sf(data = europe_high_res, fill = "lightgrey", color = "black", size = 0.2) +
  # Add background coastline
  #geom_sf(data = coastline_high_res, color = "blue", size = 0.3) +
  # Add frontier regions
  geom_sf(data = nouvelle_aquitaine, fill = NA, color = "black", size = 3) +
  geom_sf(data = BC, fill = NA, color = "black", size = 3) +
  # Add north arrow
  annotation_north_arrow(location = "tr", 
                         which_north = "true",
                         pad_x = unit(0.1, "in"), pad_y = unit(0.2, "in"),
                         style = north_arrow_fancy_orienteering,
                         height = unit(1, "cm"), width = unit(1, "cm")) +
  # Add scale bar
  annotation_scale(location = "br", width_hint = 0.3, text_cex = 0.7, 
                   pad_x = unit(0.2, "cm"), pad_y = unit(1.3, "cm"),
                   style = "bar", bar_cols = c("black", "white"),
                   line_width = 1, height = unit(0.2, "cm"),
                   text_family = "sans", text_face = "bold") +
  # Add sampling beaches
  geom_point(data = ports, aes(x = longitude, y = latitude, color = legend_pt), size = 3) +
  scale_color_manual(values = hb_color) +
  geom_text_repel(data = ports, 
                  aes(x = longitude, y = latitude, label = Port, 
                      hjust = ifelse(label_position == "left", 1.1, 
                                     ifelse(label_position == "right", -0.05, 
                                            ifelse(label_position == "top", 0.5, 
                                                   ifelse(label_position == "below", 0.5, NA)))), 
                      vjust = ifelse(label_position == "left", 0.5, 
                                     ifelse(label_position == "right", 0, 
                                            ifelse(label_position == "top", -1, 
                                                   ifelse(label_position == "below", 1.5, NA))))),
                  size = 3.5, 
                  color = "black",
                  fontface = "bold",
                  box.padding = 0.1,
                  point.padding = 0.1,
                  segment.color = "transparent") +
  coord_sf(xlim = c(-5.0, -0.2), ylim = c(42.8, 48.0)) +
  theme_minimal() +
  labs(title = "Studied area of the Plasfito research project\n",
       color = "") +
  theme(
    # panel.background = element_blank(),
    # panel.grid.major = element_blank(),
    # panel.grid.minor = element_blank(),
    axis.title.x = element_text(size = 20, face = "bold", vjust = 0.5, margin = margin(t = 10, r = 20, b = 0, l = 0)),
    axis.title.y = element_text(size = 20, face = "bold", vjust = 3, margin = margin(t = 0, r = 5, b = 0, l = 0)),
    axis.text.x = element_text(size = 12, face = 'bold'),
    axis.text.y = element_text(size = 12, face = 'bold'),
    title = element_text(size = 22, face = "bold", margin = margin(t = 10, r = 0, b = 20, l = 0)),
    strip.text = element_text(face = "bold", size = rel(2)),
    strip.background = element_rect(fill = "grey", color = "grey", linewidth = 0.1),
    legend.position = "right",
    #legend.margin = margin(t = 0, r = 0, b = 0, l = 0),
    legend.spacing.y = unit(-0.7, "cm"),
    legend.title = element_text(size = 18, face = 'bold'),
    legend.text = element_text(size = 14, face = 'bold')) +
  labs(caption = "Legend") +
  theme(plot.caption = element_text(family = "Arial",
               face = "bold",
               color = 1,
               size = 18,
               hjust = 1.23,
               vjust = 115,
               angle = 0,
               lineheight = 1))

Plasfito_ports

```


```{r Map paper}

pt_color <- c("FR1 = Le Truc Vert" = "#0039D8", 
              "FR2 = Banc d'Arguin" = "#0039D8", 
              "FR3 = Le Wharf" = "#0039D8", 
              "FR4 = Champ-de-tire" = "#0039D8", 
              "ES1 = Murgita" = "#009B48",
              "ES2 = Orrua" = "#009B48",
              "ES3 = Alkolea" = "#009B48",
              "ES4 = Gorrondatxe" = "#009B48")

Sampled_beaches$label_beach <- factor(Sampled_beaches$label_beach, 
                                      levels = c("FR1 = Le Truc Vert", 
                                                 "FR2 = Banc d'Arguin", 
                                                 "FR3 = Le Wharf", 
                                                 "FR4 = Champ-de-tire", 
                                                 "ES1 = Murgita",
                                                 "ES2 = Orrua",
                                                 "ES3 = Alkolea",
                                                 "ES4 = Gorrondatxe"))

Plasfito <- ggplot() +
  # Add white background
  geom_rect(aes(xmin = -5.2, xmax = -0.0, ymin = 42.8, ymax = 48.25), 
            fill = "white", color = NA) +
   # Add Plasfito area with legend
  geom_rect(data = studied_area_df, aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = area), 
            color = NA, alpha = 1) +
  scale_fill_manual(values = c("Studied area" = "#80CAD0"), name = "") +
  # Add background continent
  geom_sf(data = europe_high_res, fill = "lightgrey", color = "black", size = 0.2) +
  # Add frontier regions
  geom_sf(data = nouvelle_aquitaine, fill = NA, color = "black", size = 3) +
  geom_sf(data = BC, fill = NA, color = "black", size = 3) +
  # Add north arrow
  annotation_north_arrow(location = "tr", 
                         which_north = "true",
                         pad_x = unit(0.1, "in"), pad_y = unit(0.2, "in"),
                         style = north_arrow_fancy_orienteering,
                         height = unit(1, "cm"), width = unit(1, "cm")) +
  # Add scale bar
  annotation_scale(location = "br", width_hint = 0.3, text_cex = 0.7, 
                   pad_x = unit(0.2, "cm"), pad_y = unit(0.4, "cm"),
                   style = "bar", bar_cols = c("black", "white"),
                   line_width = 1, height = unit(0.2, "cm"),
                   text_family = "sans", text_face = "bold") +
  # Add sampling beaches
  geom_point(data = Sampled_beaches, aes(x = longitude, y = latitude, color = label_beach), size = 3) +
  scale_color_manual(values = pt_color) +
  geom_text_repel(data = Sampled_beaches, 
                  aes(x = longitude, y = latitude, label = code, 
                      hjust = ifelse(label_position == "right", 1.3, 0.5), 
                      vjust = ifelse(label_position == "below", 0.5, 0.5)),
                  size = 5, 
                  color = "black",
                  fontface = "bold",
                  box.padding = 0.2,
                  point.padding = 0.1,
                  segment.color = "transparent") +
  coord_sf(xlim = c(-5.0, -0.2), ylim = c(42.8, 48.0)) +
  theme_minimal() +
  labs(#title = "Studied area of the Plasfito research project",
       color = "Sampled beaches",
       fill = "") +
  theme(
    axis.title.x = element_text(size = 20, face = "bold", vjust = 0.5, margin = margin(t = 10, r = 20, b = 0, l = 0)),
    axis.title.y = element_text(size = 20, face = "bold", vjust = 3, margin = margin(t = 0, r = 5, b = 0, l = 0)),
    axis.text.x = element_text(size = 12, face = 'bold'),
    axis.text.y = element_text(size = 12, face = 'bold'),
    title = element_text(size = 22, face = "bold", margin = margin(t = 10, r = 0, b = 20, l = 0)),
    strip.text = element_text(face = "bold", size = rel(2)),
    strip.background = element_rect(fill = "grey", color = "grey", linewidth = 0.1),
    legend.position = "right",
    legend.spacing.y = unit(0.1, "cm"),
    legend.title = element_text(size = 18, face = 'bold'),
    legend.text = element_text(size = 14, face = 'bold')) +
  theme(panel.border = element_rect(color = "black", fill = NA, linewidth = 0.5)) + # Add black contour
guides(fill = guide_legend(title = "", order = 1),
    color = guide_legend(order = 2))

Plasfito 



```

```{r last method based on  Benoît Mandelbrot method}
library(geodata)
library(terra)
library(sf)
library(ggplot2)
library(dplyr)
library(tidyverse)
library(rnaturalearth)

# Get coastline data for France and Spain
france <- gadm("FRA", level=0, resolution=1, path=".")
spain <- gadm("ESP", level=0, resolution=1, path=".")

# Combine and transform to a planar coordinate system
france_sf <- st_as_sf(france)
france_proj <- st_transform(france_sf, crs = 32631) 
spain_sf <- st_as_sf(spain)
spain_proj <- st_transform(spain_sf, crs = 25830) 

# Extract the coastline
coastline_fr <- st_cast(st_geometry(france_proj), "MULTILINESTRING")
coastline_fr <- st_cast(coastline_fr, "LINESTRING")

# Extract the coastline
coastline_es <- st_cast(st_geometry(spain_proj), "MULTILINESTRING")
coastline_es <- st_cast(coastline_es, "LINESTRING")


##FRANCE
# Calculate the length of each linestring in the coastline
l <- st_length(coastline_fr)
total_length <- sum(l)
print(total_length)

i <- order(l, decreasing = TRUE)[1]
i

l[i] / 1000
## Fr size 9154.904 [km]
b_fr <- coastline_fr[i]

par(mai=rep(0,4))
plot(b_fr)

b_fr <- terra::vect(b_fr)

# Define the bounding box in geographic coordinates
lon_min <- -2  # 2°W
lon_max <- 0   # 0°
lat_min <- 43  # 43°N
lat_max <- 47  # 47°N

# Create a bounding box as an sf object
bbox <- st_as_sfc(st_bbox(c(xmin = lon_min, xmax = lon_max, 
                            ymin = lat_min, ymax = lat_max), 
                          crs = 4326))

# Transform the bounding box to match your data's CRS
# Replace XXXX with the EPSG code of your data's CRS
bbox_transformed <- st_transform(bbox, crs = 32631)

bbox_transformed2 <- terra::vect(bbox_transformed)

# Perform the intersection
b_fr_plasfito <- terra::intersect(b_fr, bbox_transformed2)

##SPAIN
l <- st_length(coastline_es)
total_length <- sum(l)
print(total_length)

i <- order(l, decreasing = TRUE)[1]
i

l[i] / 1000
## Es size 8013.248 [km]
b_es <- coastline_es[i]

par(mai=rep(0,4))
plot(b_es)

b_es <- terra::vect(b_es)

# Define the bounding box in geographic coordinates
lon_min <- -4  # 2°W
lon_max <- 0   # 0°
lat_min <- 43.2  # 43°N
lat_max <- 44  # 47°N

# Create a bounding box as an sf object
bbox <- st_as_sfc(st_bbox(c(xmin = lon_min, xmax = lon_max, 
                            ymin = lat_min, ymax = lat_max), 
                          crs = 4326))

# Transform the bounding box to match your data's CRS
# Replace XXXX with the EPSG code of your data's CRS
bbox_transformed <- st_transform(bbox, crs =25830)

bbox_transformed2 <- terra::vect(bbox_transformed)

# Perform the intersection
b_es_plasfito <- terra::intersect(b_es, bbox_transformed2)
```


```{r function to measure}
measure_with_ruler <- function(pols, length, lonlat=FALSE) {
    # Vérification du type d'objet
    stopifnot(inherits(pols, 'SpatVector'))
    stopifnot(length(pols) == 1)
    
    # Obtenir les coordonnées
    g <- crds(pols)
    nr <- nrow(g)
    
    pts <- 1
    newpt <- 1
    while(TRUE) {
        p <- newpt
        j <- p:(p+nr-1)
        j[j > nr] <- j[j > nr] - nr
        gg <- g[j,]
        
        # Utiliser la fonction distance de terra
        pd <- terra::distance(gg[1,, drop=FALSE], gg, lonlat=lonlat)
        pd <- as.vector(pd)
        
        i <- which(pd > length)[1]
        if (is.na(i)) {
            stop('Ruler is longer than the maximum distance found')
        }
        newpt <- i + p
        if (newpt >= nr) break
        pts <- c(pts, newpt)
    }
    pts <- c(pts, 1)
    g[pts, ]
}
```

```{r get the data}
y <- list()
rulers <- c(0.001) # km
for (i in 1:length(rulers)) {
    y[[i]] <- measure_with_ruler(b_fr_plasfito, rulers[i]*1000)
}

size_fr <- y

y <- list()
rulers <- c(0.001) # km
for (i in 1:length(rulers)) {
    y[[i]] <- measure_with_ruler(b_es_plasfito, rulers[i]*1000)
}
size_es <- y


```

```{r calculate the segment size France}
# Fonction pour calculer la distance euclidienne entre deux points
euclidean_distance <- function(x1, y1, x2, y2) {
  sqrt((x2 - x1)^2 + (y2 - y1)^2)
}

# Convertir la liste en dataframe
df <- as.data.frame(size_fr[[1]])
colnames(df) <- c("x", "y")

df <- df[-c(7090:7250, 7000:3900, #eliminate gironde coordinates
            3125:1970,  #eliminate arcachon coordinates
            355:315), ] #eliminate st-jean-luz bay coordinates

df <- df %>% 
  filter(!(y > 5130000)) %>% 
  filter(!(x > 187000)) %>% 
  filter(!(y < 4813100)) 


plot(df$x, df$y, type = "b", col = "blue", lwd = 2)

# Créer un objet sf à partir de vos données
line_sf <- st_sfc(st_linestring(as.matrix(df)), crs = 32631)

# Obtenir les données de la France
france <- ne_countries(scale = 10, country = "France", returnclass = "sf")

# Transformer les données de la France en UTM Zone 31N
france_utm <- st_transform(france, 32631)

# Créer la carte
ggplot() +
  geom_sf(data = france_utm, fill = "lightgrey", color = "darkgrey") +
  geom_sf(data = line_sf, color = "blue", size = 1) +
  geom_point(data = df, aes(x, y), color = "red", size = 0.5) +
  coord_sf(xlim = c(min(df$x) - 10000, max(df$x) + 1000),
           ylim = c(min(df$y) - 1000, max(df$y) + 1000),
           datum = sf::st_crs("EPSG:32631")) +
  theme_minimal() +
  labs(title = "Ligne tracée sur la carte de France",
       x = "Easting (m)",
       y = "Northing (m)") +
  scale_x_continuous(labels = function(x) format(x, scientific = FALSE)) +
  scale_y_continuous(labels = function(y) format(y, scientific = FALSE))

#plot zoom on pointe st-clement
ggplot() +
  geom_sf(data = france_utm, fill = "lightgrey", color = "darkgrey") +
  geom_sf(data = line_sf, color = "blue", size = 1) +
  geom_point(data = df, aes(x, y), color = "red", size = 0.5) +
  coord_sf(xlim = c(min(df$x) + 50000, max(df$x) - 10000),
           ylim = c(min(df$y) + 400000, max(df$y) - 50000),
           datum = sf::st_crs("EPSG:32631")) +
  theme_minimal() +
  labs(title = "Ligne tracée sur la carte de France",
       x = "Easting (m)",
       y = "Northing (m)") +
  scale_x_continuous(labels = function(x) format(x, scientific = FALSE)) +
  scale_y_continuous(labels = function(y) format(y, scientific = FALSE))

#plot zoom on pointe gironde
ggplot() +
  geom_sf(data = france_utm, fill = "lightgrey", color = "darkgrey") +
  geom_sf(data = line_sf, color = "blue", size = 1) +
  geom_point(data = df, aes(x, y), color = "red", size = 0.5) +
  coord_sf(xlim = c(min(df$x) + 50000, max(df$x) - 100),
           ylim = c(min(df$y) + 300000, max(df$y) - 100000),
           datum = sf::st_crs("EPSG:32631")) +
  theme_minimal() +
  labs(title = "Ligne tracée sur la carte de France",
       x = "Easting (m)",
       y = "Northing (m)") +
  scale_x_continuous(labels = function(x) format(x, scientific = FALSE)) +
  scale_y_continuous(labels = function(y) format(y, scientific = FALSE))

# Calculer les distances entre points consécutifs
distances <- sapply(1:(nrow(df)-1), function(i) {
  euclidean_distance(df$x[i], df$y[i], df$x[i+1], df$y[i+1])
})

#plot zoom on arcachon bay
ggplot() +
  geom_sf(data = france_utm, fill = "lightgrey", color = "darkgrey") +
  geom_sf(data = line_sf, color = "blue", size = 1) +
  geom_point(data = df, aes(x, y), color = "red", size = 0.5) +
  coord_sf(xlim = c(min(df$x) + 30000, max(df$x) - 100),
           ylim = c(min(df$y) + 220000, max(df$y) - 200000),
           datum = sf::st_crs("EPSG:32631")) +
  theme_minimal() +
  labs(title = "Ligne tracée sur la carte de France",
       x = "Easting (m)",
       y = "Northing (m)") +
  scale_x_continuous(labels = function(x) format(x, scientific = FALSE)) +
  scale_y_continuous(labels = function(y) format(y, scientific = FALSE))

#plot zoom on border fr/es
ggplot() +
  geom_sf(data = france_utm, fill = "lightgrey", color = "darkgrey") +
  geom_sf(data = line_sf, color = "blue", size = 1) +
  geom_point(data = df, aes(x, y), color = "red", size = 0.5) +
  coord_sf(xlim = c(min(df$x) - 10000, max(df$x) - 50000),
           ylim = c(min(df$y) + 40000, max(df$y) - 320000),
           datum = sf::st_crs("EPSG:32631")) +
  theme_minimal() +
  labs(title = "Ligne tracée sur la carte de France",
       x = "Easting (m)",
       y = "Northing (m)") +
  scale_x_continuous(labels = function(x) format(x, scientific = FALSE)) +
  scale_y_continuous(labels = function(y) format(y, scientific = FALSE))

# Calculer les distances entre points consécutifs
distances <- sapply(1:(nrow(df)-1), function(i) {
  euclidean_distance(df$x[i], df$y[i], df$x[i+1], df$y[i+1])
})

# Créer le dataframe final
result_df <- tibble(
  segment = 1:length(distances),
  start_x = df$x[-nrow(df)],
  start_y = df$y[-nrow(df)],
  end_x = df$x[-1],
  end_y = df$y[-1],
  distance = round(distances, 2),
  dist_km = round(distances / 1000, 2)
) %>% 
  filter(!(dist_km > 30))  # Remove segments longer than 30 m
result_df

summary_stats <- result_df %>%
  summarise(
    tot_dist_km = sum(dist_km)
  )
summary_stats
```

```{r calculate the segment size Spain}
# Fonction pour calculer la distance euclidienne entre deux points
euclidean_distance <- function(x1, y1, x2, y2) {
  sqrt((x2 - x1)^2 + (y2 - y1)^2)
}

# Convertir la liste en dataframe
df <- as.data.frame(size_es[[1]])
colnames(df) <- c("x", "y")

df <- df[-c(6355:6445,  #eliminate pasia coordinates
            5975:6045,   #eliminate orio coordinate
            4990:5100,  #eliminate mundaka coordinates
            3790:4290,  #eliminate bilbao coordinates
            2250:2930,  #eliminate santona coordinates
            1670:1830,  #eliminate faro de ajo coordinates
            630:1315  #eliminate santander coordinates
            ), ] 

df <- df %>% 
  filter(!(x > 597200)) 

plot(df$x, df$y, type = "b", col = "blue", lwd = 2)

# Create an sf object from your data
line_sf <- st_sfc(st_linestring(as.matrix(df)), crs = 25830)

# Obtenir les données de la France
spain <- ne_countries(scale = "large", country = "Spain", returnclass = "sf")

# Transform the map to UTM Zone 31N (EPSG:25830
spain_utm <- st_transform(spain, 25830)


# Create the map
ggplot() +
  geom_sf(data = spain_utm, fill = "lightgrey", color = "darkgrey") +
  geom_sf(data = line_sf, color = "blue", size = 1) +
  geom_point(data = df, aes(x, y), color = "red", size = 0.5) +
  coord_sf(xlim = c(min(df$x) - 10000, max(df$x) + 1000),
           ylim = c(min(df$y) - 1000, max(df$y) + 1000),
           datum = sf::st_crs("EPSG:25830")) +
  theme_minimal() +
  labs(title = "Ligne tracée sur la carte de France",
       x = "Easting (m)",
       y = "Northing (m)") +
  scale_x_continuous(labels = function(x) format(x, scientific = FALSE)) +
  scale_y_continuous(labels = function(y) format(y, scientific = FALSE))

# zoom border se/fr
ggplot() +
  geom_sf(data = spain_utm, fill = "lightgrey", color = "darkgrey") +
  geom_sf(data = line_sf, color = "blue", size = 1) +
  geom_point(data = df, aes(x, y), color = "red", size = 0.5) +
  coord_sf(xlim = c(min(df$x) + 220000, max(df$x) - 10000),
           ylim = c(min(df$y) - 1000, max(df$y) + 1000),
           datum = sf::st_crs("EPSG:25830")) +
  theme_minimal() +
  labs(title = "Ligne tracée sur la carte de France",
       x = "Easting (m)",
       y = "Northing (m)") +
  scale_x_continuous(labels = function(x) format(x, scientific = FALSE)) +
  scale_y_continuous(labels = function(y) format(y, scientific = FALSE))

# zoom border pasaia
ggplot() +
  geom_sf(data = spain_utm, fill = "lightgrey", color = "darkgrey") +
  geom_sf(data = line_sf, color = "blue", size = 1) +
  geom_point(data = df, aes(x, y), color = "red", size = 0.5) +
  coord_sf(xlim = c(min(df$x) + 180000, max(df$x) - 30000),
           ylim = c(min(df$y) - 1000, max(df$y) + 1000),
           datum = sf::st_crs("EPSG:25830")) +
  theme_minimal() +
  labs(title = "Ligne tracée sur la carte de France",
       x = "Easting (m)",
       y = "Northing (m)") +
  scale_x_continuous(labels = function(x) format(x, scientific = FALSE)) +
  scale_y_continuous(labels = function(y) format(y, scientific = FALSE))

# zoom santander
ggplot() +
  geom_sf(data = spain_utm, fill = "lightgrey", color = "darkgrey") +
  geom_sf(data = line_sf, color = "blue", size = 1) +
  geom_point(data = df, aes(x, y), color = "red", size = 0.5) +
  coord_sf(xlim = c(min(df$x) + 10000, max(df$x) - 140000),
           ylim = c(min(df$y) - 1000, max(df$y) + 1000),
           datum = sf::st_crs("EPSG:25830")) +
  theme_minimal() +
  labs(title = "Ligne tracée sur la carte de France",
       x = "Easting (m)",
       y = "Northing (m)") +
  scale_x_continuous(labels = function(x) format(x, scientific = FALSE)) +
  scale_y_continuous(labels = function(y) format(y, scientific = FALSE))

# zoom santona
ggplot() +
  geom_sf(data = spain_utm, fill = "lightgrey", color = "darkgrey") +
  geom_sf(data = line_sf, color = "blue", size = 1) +
  geom_point(data = df, aes(x, y), color = "red", size = 0.5) +
  coord_sf(xlim = c(min(df$x) + 30000, max(df$x) - 110000),
           ylim = c(min(df$y) - 1000, max(df$y) + 1000),
           datum = sf::st_crs("EPSG:25830")) +
  theme_minimal() +
  labs(title = "Ligne tracée sur la carte de France",
       x = "Easting (m)",
       y = "Northing (m)") +
  scale_x_continuous(labels = function(x) format(x, scientific = FALSE)) +
  scale_y_continuous(labels = function(y) format(y, scientific = FALSE))

# zoom bilbao 
ggplot() +
  geom_sf(data = spain_utm, fill = "lightgrey", color = "darkgrey") +
  geom_sf(data = line_sf, color = "blue", size = 1) +
  geom_point(data = df, aes(x, y), color = "red", size = 0.5) +
  coord_sf(xlim = c(min(df$x) + 70000, max(df$x) - 80000),
           ylim = c(min(df$y) - 1000, max(df$y) + 1000),
           datum = sf::st_crs("EPSG:25830")) +
  theme_minimal() +
  labs(title = "Ligne tracée sur la carte de France",
       x = "Easting (m)",
       y = "Northing (m)") +
  scale_x_continuous(labels = function(x) format(x, scientific = FALSE)) +
  scale_y_continuous(labels = function(y) format(y, scientific = FALSE))

# zoom border mundaka
ggplot() +
  geom_sf(data = spain_utm, fill = "lightgrey", color = "darkgrey") +
  geom_sf(data = line_sf, color = "blue", size = 1) +
  geom_point(data = df, aes(x, y), color = "red", size = 0.5) +
  coord_sf(xlim = c(min(df$x) + 100000, max(df$x) - 50000),
           ylim = c(min(df$y) - 1000, max(df$y) + 1000),
           datum = sf::st_crs("EPSG:25830")) +
  theme_minimal() +
  labs(title = "Ligne tracée sur la carte de France",
       x = "Easting (m)",
       y = "Northing (m)") +
  scale_x_continuous(labels = function(x) format(x, scientific = FALSE)) +
  scale_y_continuous(labels = function(y) format(y, scientific = FALSE))

# Calculer les distances entre points consécutifs
distances <- sapply(1:(nrow(df)-1), function(i) {
  euclidean_distance(df$x[i], df$y[i], df$x[i+1], df$y[i+1])
})

# Créer le dataframe final
result_df <- tibble(
  segment = 1:length(distances),
  start_x = df$x[-nrow(df)],
  start_y = df$y[-nrow(df)],
  end_x = df$x[-1],
  end_y = df$y[-1],
  distance = round(distances, 2),
  dist_km = round(distances / 1000, 2)
) %>% 
  filter(!(dist_km > 30))  # Remove segments longer than 30 m
result_df

summary_stats_es <- result_df %>%
  summarise(
    tot_dist_km = sum(dist_km)
  )
summary_stats_es
```

```{r Global coastline size}
Plasfito_coast_size <- summary_stats$tot_dist_km + summary_stats_es$tot_dist_km
Plasfito_coast_size
```
